// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi
{
    public partial class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int? GenderId { get; set; }

        public virtual Gender Gender { get; set; }
    }
}